python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 0
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 1
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 2
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 3
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 4
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 5
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 6
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 7
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 8
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 9
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 0
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 11
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 12
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 13
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 14
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 15
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 16
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 17
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 18
python train.py --device cuda:0 --dataset Amazon-Photo --param local:amazon_photo.json --drop_scheme degree --seed 19