CiteSeer:
  activation: prelu
  base_model: GCNConv
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.0
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  learning_rate: 0.001
  num_epochs: 200
  num_hidden: 256
  num_layers: 2
  num_proj_hidden: 256
  seed: 38108
  tau: 0.9
  weight_decay: 1.0e-05
  pos_tau: 10
  neg_tau: 0.001
  f_weight: 0.9
Cora:
  activation: relu
  base_model: GCNConv
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  learning_rate: 0.0005
  num_epochs: 200
  num_hidden: 128
  num_layers: 2
  num_proj_hidden: 128
  seed: 39788
  tau: 0.4
  weight_decay: 1.0e-05
  pos_tau: 0.1
  neg_tau: 0.1
  f_weight: 0.6
DBLP:
  activation: relu
  base_model: GCNConv
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.0
  learning_rate: 0.001
  num_epochs: 1000
  num_hidden: 256
  num_layers: 2
  num_proj_hidden: 256
  seed: 83521
  tau: 0.7
  weight_decay: 1.0e-05
  pos_tau: 10
  neg_tau: 10
  f_weight: 0.5
PubMed:
  activation: relu
  base_model: GCNConv
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  learning_rate: 0.001
  num_epochs: 1500
  num_hidden: 256
  num_layers: 2
  num_proj_hidden: 256
  seed: 23344
  tau: 0.7
  weight_decay: 1.0e-05
  pos_tau: 1
  neg_tau: 0.1
  f_weight: 0.7